#####################
###   DSA model   ###
#####################

res_dsa<-as.data.frame(matrix(ncol = 7,nrow = 32))
colnames(res_dsa)<-c("Param","ICER1_lower","ICER1_upper","ICER2_lower","ICER2_upper","ICER3_lower","ICER3_upper")
res_dsa$Param<-c("p_s2d","p_m2d","p_hf2d","p_ps2d","p_pm2d","p_phf2d","c_uc_p","c_uc_h","c_ls_p","c_ls_h","c_sex_p","c_sex_h","c_rex_p","c_rex_h",
                 "c_di_p","c_di_h","c_s","c_m","c_hf","c_ps","c_pm","c_phf","u_h","u_s","u_m","u_hf","u_ps","u_pm","u_phf","c_drug","c_eof","disu")
#########################
###   Run the model   ###
#########################
i=1
p_s2d=fun1(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
p_s2d=fun1(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
p_s2d=fun1(1)

i=2
p_m2d=fun2(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
p_m2d=fun2(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
p_m2d=fun2(1)

i=3
p_hf2d=fun3(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
p_hf2d=fun3(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
p_hf2d=fun3(1)

i=4
p_ps2d=fun4(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
p_ps2d=fun4(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
p_ps2d=fun4(1)

i=5
p_pm2d=fun5(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
p_pm2d=fun5(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
p_pm2d=fun5(1)

i=6
p_phf2d=fun6(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
p_phf2d=fun6(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
p_phf2d=fun6(1)

i=7
c_uc_p=fun7(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_uc_p=fun7(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_uc_p=fun7(1)

i=8
c_uc_h=fun8(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_uc_h=fun8(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_uc_h=fun8(1)

i=9
c_ls_p=fun9(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_ls_p=fun9(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_ls_p=fun9(1)

i=10
c_ls_h=fun10(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_ls_h=fun10(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_ls_h=fun10(1)

i=11
c_sex_p=fun11(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_sex_p=fun11(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_sex_p=fun11(1)

i=12
c_sex_h=fun12(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_sex_h=fun12(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_sex_h=fun12(1)

i=13
c_rex_p=fun13(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_rex_p=fun13(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_rex_p=fun13(1)

i=14
c_rex_h=fun14(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_rex_h=fun14(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_rex_h=fun14(1)

i=15
c_di_p=fun15(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_di_p=fun15(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_di_p=fun15(1)

i=16
c_di_h=fun16(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_di_h=fun16(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_di_h=fun16(1)

i=17
c_s=fun17(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_s=fun17(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_s=fun17(1)

i=18
c_m=fun18(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_m=fun18(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_m=fun18(1)

i=19
c_hf=fun19(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_hf=fun19(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_hf=fun19(1)

i=20
c_ps=fun20(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_ps=fun20(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_ps=fun20(1)

i=21
c_pm=fun21(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_pm=fun21(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_pm=fun21(1)

i=22
c_phf=fun22(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_phf=fun22(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_phf=fun22(1)

i=23
u_h=fun23(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
u_h=fun23(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
u_h=fun23(1)

i=24
u_s=fun24(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
u_s=fun24(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
u_s=fun24(1)

i=25
u_m=fun25(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
u_m=fun25(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
u_m=fun25(1)

i=26
u_hf=fun26(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
u_hf=fun26(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
u_hf=fun26(1)

i=27
u_ps=fun27(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
u_ps=fun27(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
u_ps=fun27(1)

i=28
u_pm=fun28(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
u_pm=fun28(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
u_pm=fun28(1)

i=29
u_phf=fun29(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
u_phf=fun29(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
u_phf=fun29(1)

i=30
c_drug=fun30(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_drug=fun30(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_drug=fun30(1)

i=31
c_eof=fun31(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
c_eof=fun31(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
c_eof=fun31(1)

i=32
disu=fun32(2)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_lower[i]=res_temp$icer[1]
res_dsa$ICER2_lower[i]=res_temp$icer[2]
res_dsa$ICER3_lower[i]=res_temp$icer[3]
disu=fun32(3)
source("pre-cea-model.R")
source("base-case-analysis.R")
res_temp=ICER_outcome()[[2]]
res_dsa$ICER1_upper[i]=res_temp$icer[1]
res_dsa$ICER2_upper[i]=res_temp$icer[2]
res_dsa$ICER3_upper[i]=res_temp$icer[3]
disu=fun32(1)
